version: "2.4"
services:
  d2r-terrorzones:
    build: .
    image: d2r-terrorzones:${TAG}
    labels:
      - "com.centurylinklabs.watchtower.enable=false"  #  watchtower should not try to monitor and update
    environment:
      - PUBLIC_REPO=https://github.com/MyNameIs-13/TerrorZones-Discord
    env_file:
      - .secrets
    restart: always
    cap_drop:
      - ALL
    volumes:
      - "${LOGPATH:-/}:/app/logs"
      - "${ZONEINFOPATH:-/}:/app/zone-info"
    user: ${UID:-65534}:${GID:-65534}
    pids_limit: 3  # program & for some reason healthcheck needs 2
    scale: 1
    cpus: 0.2
    mem_limit: 100M
    mem_reservation: 25M